### ISSUE TITLE
Generated JavaScript client's getIp defaults returnType to Ip instead of schema

### ISSUE THREAD

**Issue by cliffano** [oapicf/openapi-ipify#13]
As of OAG 5.4.0, Ipify spec defines response 200 with multiple content types:
```
      responses:
        '200':
          description: Your public IP address
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Ip"
            'application/javascript':
              schema:
                type: string
            'text/plain':
              schema:
                type: string
```
However, the generated `getIp` function defaults returnType to `Ip`, which is only correct for `application/json`, while `application/javascript` and 'text/plain` should have string returnType.
This causes a problem where getIp with plain text string containing the IP address value is wrapped into Ip model which contains undefined ip property.
```
    getIp(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'format': opts['format'],
        'callback': opts['callback']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/javascript', 'text/plain'];
      let returnType = Ip;
      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
```
Ideally the returnTypes should be a map, and then apiClient.callApi should decide which returnType to be used depending on the response content-type header.

This problem could be due to the fact that OAG only loaded the first one when encountering multiple schemas as content.
```
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
```

**Comment by spacether** [comment]
If you switch to the latest openapi Json Schema generator it will return a different response instance for each of those content types and it will allow you to pass in the accept header to select one.

**Comment by cliffano** [comment]
Dropping this need starting from v5.3.0, and opted to simply accept string as the response for all content types, across all clients.

I last tested the multi content types on OAG 7.6.0 and still observed the first schema being picked up.

Thanks for the info spacether. I'll look into it the next time I have more bandwidth for this library.
